version: "3.8"

services:
  backend:
    build: ./backend
    container_name: nest-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://backend:3000/api"
    container_name: react-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
